import type { ActionId } from '@/domain/shared/ids';
import type { ResponseLanguageCode } from '@/shared/constants/response-languages';
import { BUILTIN_ACTIONS_RU } from '@/shared/constants/i18n/builtin-actions.ru';
import { BUILTIN_ACTIONS_UK } from '@/shared/constants/i18n/builtin-actions.uk';
import {
  resolveActionLocale,
  type ActionLocale,
} from '@/shared/utils/resolve-action-locale';

export interface LocalizedActionText {
  name: string;
  prompt: string;
}

import {
  THOROUGH_TRANSLATE,
  MAXIMAL_TRANSLATE,
} from '@/shared/constants/localized-translation-actions.special';

const SPECIAL_LOCALIZED: Record<string, Record<ActionLocale, LocalizedActionText>> = {
  act_thorough_translate: THOROUGH_TRANSLATE,
  act_maximal_translate: MAXIMAL_TRANSLATE,
};

const LOCALE_PACKS: Partial<Record<ActionLocale, Record<string, LocalizedActionText>>> = {
  ru: BUILTIN_ACTIONS_RU,
  uk: BUILTIN_ACTIONS_UK,
};

const ACTION_NAMES: Partial<Record<ActionLocale, Record<string, string>>> = {
  de: {
    act_explain: 'Erklären',
    act_translate: 'Übersetzen',
    act_ask: 'Fragen',
    act_rewrite: 'Umschreiben',
    act_summarize: 'Zusammenfassen',
    act_code_review: 'Code-Review',
    act_grammar: 'Grammatik',
    act_tone_formal: 'Formeller Ton',
    act_tone_casual: 'Lockerer Ton',
    act_expand: 'Erweitern',
    act_shorten: 'Kürzen',
    act_detect_lang: 'Sprache erkennen',
    act_ipa: 'IPA',
    act_etymology: 'Etymologie',
    act_examples: 'Beispiele',
    act_explain_code: 'Code erklären',
    act_refactor: 'Refaktorieren',
    act_debug: 'Debuggen',
    act_gen_tests: 'Tests generieren',
    act_optimize: 'Optimieren',
    act_add_docs: 'Dokumentation',
    act_simple: 'Einfache Worte',
    act_quiz: 'Quiz',
    act_flashcard: 'Karteikarte',
    act_key_concepts: 'Schlüsselkonzepte',
    act_pros_cons: 'Pro & Contra',
    act_fact_check: 'Faktencheck',
    act_compare: 'Vergleichen',
    act_action_items: 'Aufgaben',
    act_email: 'E-Mail-Entwurf',
    act_explain_screenshot: 'Screenshot erklären',
  },
  fr: {
    act_explain: 'Expliquer',
    act_translate: 'Traduire',
    act_ask: 'Demander',
    act_rewrite: 'Réécrire',
    act_summarize: 'Résumer',
    act_code_review: 'Revue de code',
    act_grammar: 'Grammaire',
    act_tone_formal: 'Ton formel',
    act_tone_casual: 'Ton décontracté',
    act_expand: 'Développer',
    act_shorten: 'Raccourcir',
    act_detect_lang: 'Détecter la langue',
    act_ipa: 'API',
    act_etymology: 'Étymologie',
    act_examples: 'Exemples',
    act_explain_code: 'Expliquer le code',
    act_refactor: 'Refactoriser',
    act_debug: 'Déboguer',
    act_gen_tests: 'Générer des tests',
    act_optimize: 'Optimiser',
    act_add_docs: 'Documentation',
    act_simple: 'Mots simples',
    act_quiz: 'Quiz',
    act_flashcard: 'Fiche',
    act_key_concepts: 'Concepts clés',
    act_pros_cons: 'Pour et contre',
    act_fact_check: 'Vérification',
    act_compare: 'Comparer',
    act_action_items: 'Tâches',
    act_email: 'Brouillon e-mail',
  },
  es: {
    act_explain: 'Explicar',
    act_translate: 'Traducir',
    act_ask: 'Preguntar',
    act_rewrite: 'Reescribir',
    act_summarize: 'Resumir',
    act_code_review: 'Revisión de código',
    act_grammar: 'Gramática',
    act_tone_formal: 'Tono formal',
    act_tone_casual: 'Tono casual',
    act_expand: 'Ampliar',
    act_shorten: 'Acortar',
    act_detect_lang: 'Detectar idioma',
    act_ipa: 'AFI',
    act_etymology: 'Etimología',
    act_examples: 'Ejemplos',
    act_explain_code: 'Explicar código',
    act_refactor: 'Refactorizar',
    act_debug: 'Depurar',
    act_gen_tests: 'Generar tests',
    act_optimize: 'Optimizar',
    act_add_docs: 'Documentación',
    act_simple: 'Palabras simples',
    act_quiz: 'Quiz',
    act_flashcard: 'Ficha',
    act_key_concepts: 'Conceptos clave',
    act_pros_cons: 'Pros y contras',
    act_fact_check: 'Verificación',
    act_compare: 'Comparar',
    act_action_items: 'Tareas',
    act_email: 'Borrador de email',
  },
  pl: {
    act_explain: 'Wyjaśnij',
    act_translate: 'Tłumacz',
    act_ask: 'Zapytaj',
    act_rewrite: 'Przepisz',
    act_summarize: 'Streszcz',
    act_code_review: 'Przegląd kodu',
    act_grammar: 'Gramatyka',
    act_tone_formal: 'Ton formalny',
    act_tone_casual: 'Ton swobodny',
    act_expand: 'Rozwiń',
    act_shorten: 'Skróć',
    act_detect_lang: 'Wykryj język',
    act_ipa: 'IPA',
    act_etymology: 'Etymologia',
    act_examples: 'Przykłady',
    act_explain_code: 'Wyjaśnij kod',
    act_refactor: 'Refaktoryzuj',
    act_debug: 'Debuguj',
    act_gen_tests: 'Generuj testy',
    act_optimize: 'Optymalizuj',
    act_add_docs: 'Dokumentacja',
    act_simple: 'Proste słowa',
    act_quiz: 'Quiz',
    act_flashcard: 'Fiszka',
    act_key_concepts: 'Kluczowe pojęcia',
    act_pros_cons: 'Za i przeciw',
    act_fact_check: 'Fact-check',
    act_compare: 'Porównaj',
    act_action_items: 'Zadania',
    act_email: 'Szkic e-maila',
  },
  it: {
    act_explain: 'Spiega',
    act_translate: 'Traduci',
    act_ask: 'Chiedi',
    act_rewrite: 'Riscrivi',
    act_summarize: 'Riassumi',
    act_code_review: 'Revisione codice',
    act_grammar: 'Grammatica',
    act_tone_formal: 'Tono formale',
    act_tone_casual: 'Tono informale',
    act_expand: 'Espandi',
    act_shorten: 'Accorcia',
    act_detect_lang: 'Rileva lingua',
    act_ipa: 'IPA',
    act_etymology: 'Etimologia',
    act_examples: 'Esempi',
    act_explain_code: 'Spiega codice',
    act_refactor: 'Refactoring',
    act_debug: 'Debug',
    act_gen_tests: 'Genera test',
    act_optimize: 'Ottimizza',
    act_add_docs: 'Documentazione',
    act_simple: 'Parole semplici',
    act_quiz: 'Quiz',
    act_flashcard: 'Flashcard',
    act_key_concepts: 'Concetti chiave',
    act_pros_cons: 'Pro e contro',
    act_fact_check: 'Fact-check',
    act_compare: 'Confronta',
    act_action_items: 'Attività',
    act_email: 'Bozza email',
  },
  pt: {
    act_explain: 'Explicar',
    act_translate: 'Traduzir',
    act_ask: 'Perguntar',
    act_rewrite: 'Reescrever',
    act_summarize: 'Resumir',
    act_code_review: 'Revisão de código',
    act_grammar: 'Gramática',
    act_tone_formal: 'Tom formal',
    act_tone_casual: 'Tom casual',
    act_expand: 'Expandir',
    act_shorten: 'Encurtar',
    act_detect_lang: 'Detectar idioma',
    act_ipa: 'AFI',
    act_etymology: 'Etimologia',
    act_examples: 'Exemplos',
    act_explain_code: 'Explicar código',
    act_refactor: 'Refatorar',
    act_debug: 'Depurar',
    act_gen_tests: 'Gerar testes',
    act_optimize: 'Otimizar',
    act_add_docs: 'Documentação',
    act_simple: 'Palavras simples',
    act_quiz: 'Quiz',
    act_flashcard: 'Flashcard',
    act_key_concepts: 'Conceitos-chave',
    act_pros_cons: 'Prós e contras',
    act_fact_check: 'Verificação',
    act_compare: 'Comparar',
    act_action_items: 'Tarefas',
    act_email: 'Rascunho de e-mail',
  },
  ja: {
    act_explain: '説明',
    act_translate: '翻訳',
    act_ask: '質問',
    act_rewrite: '書き換え',
    act_summarize: '要約',
    act_code_review: 'コードレビュー',
    act_grammar: '文法',
    act_tone_formal: 'フォーマル',
    act_tone_casual: 'カジュアル',
    act_expand: '拡張',
    act_shorten: '短縮',
    act_detect_lang: '言語検出',
    act_ipa: 'IPA',
    act_etymology: '語源',
    act_examples: '用例',
    act_explain_code: 'コード説明',
    act_refactor: 'リファクタ',
    act_debug: 'デバッグ',
    act_gen_tests: 'テスト生成',
    act_optimize: '最適化',
    act_add_docs: 'ドキュメント',
    act_simple: 'やさしい説明',
    act_quiz: 'クイズ',
    act_flashcard: 'フラッシュカード',
    act_key_concepts: '重要概念',
    act_pros_cons: '長所と短所',
    act_fact_check: 'ファクトチェック',
    act_compare: '比較',
    act_action_items: 'タスク',
    act_email: 'メール草案',
  },
  zh: {
    act_explain: '解释',
    act_translate: '翻译',
    act_ask: '提问',
    act_rewrite: '改写',
    act_summarize: '摘要',
    act_code_review: '代码审查',
    act_grammar: '语法',
    act_tone_formal: '正式语气',
    act_tone_casual: '随意语气',
    act_expand: '扩展',
    act_shorten: '缩短',
    act_detect_lang: '检测语言',
    act_ipa: 'IPA',
    act_etymology: '词源',
    act_examples: '用例',
    act_explain_code: '解释代码',
    act_refactor: '重构',
    act_debug: '调试',
    act_gen_tests: '生成测试',
    act_optimize: '优化',
    act_add_docs: '文档',
    act_simple: '简单解释',
    act_quiz: '测验',
    act_flashcard: '闪卡',
    act_key_concepts: '关键概念',
    act_pros_cons: '利弊',
    act_fact_check: '事实核查',
    act_compare: '比较',
    act_action_items: '待办',
    act_email: '邮件草稿',
  },
};

const PROMPT_INTRO: Record<Exclude<ActionLocale, 'en' | 'ru' | 'uk'>, string> = {
  de: 'Führe die folgende Aufgabe aus. Antworte vollständig auf Deutsch.',
  fr: 'Effectue la tâche suivante. Réponds entièrement en français.',
  es: 'Realiza la siguiente tarea. Responde completamente en español.',
  pl: 'Wykonaj następujące zadanie. Odpowiedz w całości po polsku.',
  it: 'Esegui il compito seguente. Rispondi interamente in italiano.',
  pt: 'Execute a tarefa a seguir. Responda inteiramente em português.',
  ja: '次のタスクを実行してください。回答はすべて日本語で書いてください。',
  zh: '执行以下任务。请完全用中文回答。',
};

function localizeFallback(
  actionId: string,
  locale: ActionLocale,
  fallback: LocalizedActionText,
): LocalizedActionText {
  if (locale === 'en') return fallback;

  const name = ACTION_NAMES[locale]?.[actionId] ?? fallback.name;
  const intro = PROMPT_INTRO[locale as keyof typeof PROMPT_INTRO];
  if (!intro) return { name, prompt: fallback.prompt };

  return {
    name,
    prompt: `${intro}\n\n${fallback.prompt}`,
  };
}

export function getLocalizedActionText(
  actionId: ActionId,
  responseLanguage: ResponseLanguageCode,
  languageHint?: string,
  fallback?: LocalizedActionText,
): LocalizedActionText | null {
  const locale = resolveActionLocale(responseLanguage, languageHint);

  const special = SPECIAL_LOCALIZED[actionId]?.[locale];
  if (special) return special;

  const pack = LOCALE_PACKS[locale]?.[actionId];
  if (pack) return pack;

  if (fallback) {
    return localizeFallback(actionId, locale, fallback);
  }

  return null;
}
